version: '3.7'
services:
  app:
    # context: .
    image: pedrolucaspalma/cal_ts_api
    env_file: .env
    container_name: cal_ts_api
    depends_on:
      - cal_db
    links:
      - cal_db
    volumes:
      - .:/home/pedropalma/cal-ts-api
      - /home/pedropalma/cal-ts-api/node_modules
      - ./files:/home/pedropalma/cal-ts-api/files
    ports: 
      - "8080:8080"
  cal_db:
    image: postgres:11.12
    container_name: cal_ts_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cal_ts
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  pgdata:
    driver: local
